name:                prim
version:             0.1.0.0
github:              "githubuser/prim"
license:             BSD3
author:              "Simo Levanto"
maintainer:          "simo.levanto@helsinki"
copyright:           "2022 Simo Levanto, MIT License"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prim#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  prim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prim

tests:
  prim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prim
